/**
 * The ported serverlys.com archive — 71 posts that were live and indexed
 * before this rebuild. GENERATED by scripts/port-legacy-articles.mjs from
 * ~/Desktop/Archive/blog, then edited by hand for the claims the originals
 * made that this site's editorial rules forbid.
 *
 * Do NOT re-run the generator over these files without re-applying that pass:
 * it reads the unedited source and would restore every claim that was removed.
 */
import { article as ai_tools_small_business } from "./ai-tools-small-business";
import { article as best_free_wordpress_themes } from "./best-free-wordpress-themes";
import { article as best_hosting_startups } from "./best-hosting-startups";
import { article as best_web_hosting_small_business } from "./best-web-hosting-small-business";
import { article as best_wordpress_hosting_2026 } from "./best-wordpress-hosting-2026";
import { article as build_website_from_scratch } from "./build-website-from-scratch";
import { article as cdn_setup_guide } from "./cdn-setup-guide";
import { article as cloud_vs_shared_hosting } from "./cloud-vs-shared-hosting";
import { article as contact_form_guide } from "./contact-form-guide";
import { article as conversion_rate_optimization } from "./conversion-rate-optimization";
import { article as core_web_vitals_guide } from "./core-web-vitals-guide";
import { article as cpanel_beginners_guide } from "./cpanel-beginners-guide";
import { article as cpanel_vs_plesk } from "./cpanel-vs-plesk";
import { article as database_optimization } from "./database-optimization";
import { article as dns_records_explained } from "./dns-records-explained";
import { article as domain_name_generators } from "./domain-name-generators";
import { article as domain_name_seo } from "./domain-name-seo";
import { article as domain_parking_guide } from "./domain-parking-guide";
import { article as domain_transfer_guide } from "./domain-transfer-guide";
import { article as downtime_cost_calculator } from "./downtime-cost-calculator";
import { article as email_security_spf_dkim_dmarc } from "./email-security-spf-dkim-dmarc";
import { article as expired_domains_guide } from "./expired-domains-guide";
import { article as free_ssl_setup } from "./free-ssl-setup";
import { article as freelancer_vs_agency } from "./freelancer-vs-agency";
import { article as gdpr_website_compliance } from "./gdpr-website-compliance";
import { article as google_analytics_4_guide } from "./google-analytics-4-guide";
import { article as google_analytics_setup } from "./google-analytics-setup";
import { article as google_pagespeed_score } from "./google-pagespeed-score";
import { article as green_web_hosting } from "./green-web-hosting";
import { article as gzip_vs_brotli } from "./gzip-vs-brotli";
import { article as hosting_red_flags } from "./hosting-red-flags";
import { article as hosting_uptime_explained } from "./hosting-uptime-explained";
import { article as htaccess_redirects } from "./htaccess-redirects";
import { article as http3_quic_guide } from "./http3-quic-guide";
import { article as image_optimization_web } from "./image-optimization-web";
import { article as install_wordpress_guide } from "./install-wordpress-guide";
import { article as litespeed_vs_apache_nginx } from "./litespeed-vs-apache-nginx";
import { article as local_seo_guide } from "./local-seo-guide";
import { article as malware_scanning_tools } from "./malware-scanning-tools";
import { article as managed_hosting_guide } from "./managed-hosting-guide";
import { article as migrate_website_new_host } from "./migrate-website-new-host";
import { article as mobile_speed_optimization } from "./mobile-speed-optimization";
import { article as must_have_wordpress_plugins } from "./must-have-wordpress-plugins";
import { article as mysql_database_guide } from "./mysql-database-guide";
import { article as nameservers_explained } from "./nameservers-explained";
import { article as nvme_vs_ssd_hosting } from "./nvme-vs-ssd-hosting";
import { article as online_store_setup_guide } from "./online-store-setup-guide";
import { article as reduce_ttfb } from "./reduce-ttfb";
import { article as setup_business_email } from "./setup-business-email";
import { article as speed_up_wordpress } from "./speed-up-wordpress";
import { article as ssl_certificate_explained } from "./ssl-certificate-explained";
import { article as stop_ddos_attacks } from "./stop-ddos-attacks";
import { article as subdomain_vs_subdirectory } from "./subdomain-vs-subdirectory";
import { article as tld_comparison_guide } from "./tld-comparison-guide";
import { article as two_factor_authentication } from "./two-factor-authentication";
import { article as web_application_firewall } from "./web-application-firewall";
import { article as web_hosting_cost_2026 } from "./web-hosting-cost-2026";
import { article as website_backup_strategy } from "./website-backup-strategy";
import { article as website_backup_tutorial } from "./website-backup-tutorial";
import { article as website_caching_guide } from "./website-caching-guide";
import { article as website_cost_guide } from "./website-cost-guide";
import { article as website_hacked_recovery } from "./website-hacked-recovery";
import { article as website_security_checklist } from "./website-security-checklist";
import { article as website_speed_seo } from "./website-speed-seo";
import { article as whois_privacy_protection } from "./whois-privacy-protection";
import { article as woocommerce_vs_shopify } from "./woocommerce-vs-shopify";
import { article as wordpress_security_guide } from "./wordpress-security-guide";
import { article as wordpress_seo_guide } from "./wordpress-seo-guide";
import { article as wordpress_staging_site } from "./wordpress-staging-site";
import { article as wordpress_vs_webflow_squarespace } from "./wordpress-vs-webflow-squarespace";
import { article as wordpress_white_screen_death } from "./wordpress-white-screen-death";
import type { Article } from "../types";

export const legacyArticles: readonly Article[] = [
  ai_tools_small_business,
  best_free_wordpress_themes,
  best_hosting_startups,
  best_web_hosting_small_business,
  best_wordpress_hosting_2026,
  build_website_from_scratch,
  cdn_setup_guide,
  cloud_vs_shared_hosting,
  contact_form_guide,
  conversion_rate_optimization,
  core_web_vitals_guide,
  cpanel_beginners_guide,
  cpanel_vs_plesk,
  database_optimization,
  dns_records_explained,
  domain_name_generators,
  domain_name_seo,
  domain_parking_guide,
  domain_transfer_guide,
  downtime_cost_calculator,
  email_security_spf_dkim_dmarc,
  expired_domains_guide,
  free_ssl_setup,
  freelancer_vs_agency,
  gdpr_website_compliance,
  google_analytics_4_guide,
  google_analytics_setup,
  google_pagespeed_score,
  green_web_hosting,
  gzip_vs_brotli,
  hosting_red_flags,
  hosting_uptime_explained,
  htaccess_redirects,
  http3_quic_guide,
  image_optimization_web,
  install_wordpress_guide,
  litespeed_vs_apache_nginx,
  local_seo_guide,
  malware_scanning_tools,
  managed_hosting_guide,
  migrate_website_new_host,
  mobile_speed_optimization,
  must_have_wordpress_plugins,
  mysql_database_guide,
  nameservers_explained,
  nvme_vs_ssd_hosting,
  online_store_setup_guide,
  reduce_ttfb,
  setup_business_email,
  speed_up_wordpress,
  ssl_certificate_explained,
  stop_ddos_attacks,
  subdomain_vs_subdirectory,
  tld_comparison_guide,
  two_factor_authentication,
  web_application_firewall,
  web_hosting_cost_2026,
  website_backup_strategy,
  website_backup_tutorial,
  website_caching_guide,
  website_cost_guide,
  website_hacked_recovery,
  website_security_checklist,
  website_speed_seo,
  whois_privacy_protection,
  woocommerce_vs_shopify,
  wordpress_security_guide,
  wordpress_seo_guide,
  wordpress_staging_site,
  wordpress_vs_webflow_squarespace,
  wordpress_white_screen_death,
];
